// import & define all of icons & images uses in prj here

export const images = {
    sim5g: require("../assets/fiveg.png"),
    sim: require("../assets/subs.png"),
    simlist: require("../../assets/ic_simlist.png"),
    searchlist: require("../../assets/ic_searchlist.png"),
    rose: require("../assets/rose.png"),
    important: require("../assets/important.png"),
    retailsales: require("../assets/retailsales.png"),
    terminaldevice: require("../assets/device.png"),
    phone: require("../assets/terminal.png"),
    percent: require("../../assets/percent.png"),
    vas: require("../../assets/ic_vashoa.png"),
    dropdown: require("../../assets/dropdown.png"),
    customer: require("../assets/cus.png"),
    nonesim: require("../assets/nonesim.png"),
    kpiByMonth: require('../../assets/ic_KPIbymonth.png'),
    salaryByMonth: require('../../assets/ic_salarybymonth.png'),
    avgIcome: require('../../assets/ic_avgIncome.png'),
    subscriberQuality: require('../../assets/ic_subscriberQuality.png'),
    transactionInformation: require('../../assets/ic_transactionInformation.png'),
    upSalary: require('../../assets/ic_luongkhoan.png'),
    incentive: require('../../assets/incentive.png'),
    incentiveCost: require('../../assets/ic_incentiveCost.png'),
    punishment: require('../../assets/ic_punishment.png'),
    otherExpenses: require('../../assets/ic_otherExpenses.png'),
    arrowdown: require('../../assets/dropdown.png'),
    otheroutcome: require('../../assets/otheroutcome.png'),
    headphone: require('../../assets/headphone.png'),
    arrears: require('../../assets/arrears.png'),
    debtPercent: require('../../assets/ic_debtPercent.png'),
    totalDebtNinety: require('../../assets/ic_totalDebtNinety.png'),
    totalRevenue: require('../../assets/ic_totalRevenue.png'),
    newSubPrePaid: require('../../assets/ic_newSubPrePaid.png'),
    revokeAmount: require('../../assets/ic_revokeAmount.png'),
    preToPostPaid: require('../../assets/ic_preToPostPaid.png'),
    denyTwoC: require('../../assets/ic_denyTwoC.png'),
    profileHeader: require('../../assets/profileheader.png'),
    avatar: require('../../assets/avatar.jpg'),
    day: require('../../assets/ic_day.png'),
    workingShop: require('../../assets/ic_workingShop.png'),
    traderRating: require('../../assets/ic_traderRating.png'),
    pdf: require('../../assets/ic_pdf.png'),
    home: require('../../assets/home.png'),
    user: require('../../assets/user.png'),
    logout: require('../../assets/logout.png'),
    logoutbg: require('../../assets/logoutbg.png'),
    cancle:require('../assets/cancle.png'),
    check:require('../assets/check.png'),
    splashshape:require('../../assets/splashshape.png'),
    logo:require('../../assets/logo.png'),
    loginbg:require("../../assets/loginbg.png"),
    mblogo:require("../../assets/mblogo.png"),
    pencil:require("../../assets/pencil.png"),
    close:require('../../assets/close.png'),
    man:require('../../assets/man.png'),
    back:require("../../assets/backicon.png"),
    productivitySub: require("../assets/ic_productivitySub.png"),
    company: require("../assets/ic_company.png"),
    branch: require("../assets/ic_branch.png"),
    store: require("../assets/ic_store.png"),
    skynet: require("../assets/SKYNET.png"),
    foneCardNoMoney: require("../assets/ic_foneCardNoMoney.png"),
    transAmount: require("../assets/ic_transcAmount.png"),
    contractDebt: require("../assets/ic_contractdebt.png"),
    eye:require("../assets/eye.png"),
    money:require("../../assets/money.png"),
    growth:require("../../assets/growth.png"),
    unitInformation: require("../../assets/ic_unitinformation.png"),
    toptellers: require("../../assets/ic_toptellers.png"),
    groupkpi: require("../../assets/ic_groupkpi.png"),
    teamwork: require("../../assets/teamwork.png"),
    shop: require("../assets/shop.png"),

    
}